apiVersion: v1
kind: Service
metadata:
  name: time-api-svc
  labels:
    app: time-api
    service: time-api-svc
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: time-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: time-api
  labels:
    account: timeuser
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-api-deploy
  labels:
    app: time-api
    ver: 0.1.4
    environment: production
    release: time-api-stable
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 2
  selector:
    matchLabels:
      app: time-api
      ver: 0.1.4
    matchExpressions:
      - {key: environment, operator: In, values: [production]}
  template:
    metadata:
      labels:
        app: time-api
        ver: 0.1.4
        environment: production
    spec:
      containers:
      - name: time-api-container
        image: harbor.shared.12factor.xyz/natarajmb/demo-flask-app:latest 
        imagePullPolicy: Always
        env:
         - name: PGHOST
           valueFrom:
             secretKeyRef:
               name: test-app-user-db-secret
               key: host
               optional: false
         - name: PGUSER
           valueFrom:
             secretKeyRef:
               name: test-app-user-db-secret
               key: username
               optional: false
         - name: PGDATABASE
           valueFrom:
             secretKeyRef:
               name: test-app-user-db-secret
               key: database
               optional: false
         - name: PGPASSWORD
           valueFrom:
             secretKeyRef:
               name: test-app-user-db-secret
               key: password
               optional: false
         - name: PORT
           value: "5000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---