---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: test
spec:
  #
  # Global features
  #
  pgConfig:
    dbname: test
    username: pgadmin
    appUser: test
  postgresVersion:
    name: postgres-14 # View available versions with `kubectl get postgresversion`
  serviceType: ClusterIP
#  serviceAnnotations:
  seccompProfile:
    type: RuntimeDefault
  imagePullSecret:
    name: vmware
  #  highAvailability:
  #    enabled: true
  #  logLevel: Debug
  #  backupLocation:
  #    name: backuplocation-sample
  #  certificateSecretName:

  #
  # Data Pod features
  #
  storageClassName: local-path
  storageSize: 800M
  cpu: "0.8"
  memory: 800Mi
  dataPodConfig:
#    tolerations:
#      - key:
#        operator:
#        value:
#        effect:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - data
                      - monitor
                  - key: postgres-instance
                    operator: In
                    values:
                      - test
              topologyKey: kubernetes.io/hostname
            weight: 100


  #
  # Monitor Pod features
  #
  monitorStorageClassName: local-path
  monitorStorageSize: 1G
  monitorPodConfig:
#    tolerations:
#      - key:
#        operator:
#        value:
#        effect:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - data
                      - monitor
                  - key: postgres-instance
                    operator: In
                    values:
                      - test
              topologyKey: kubernetes.io/hostname
            weight: 100

  #
  # Resources
  #
  resources:
    monitor:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 800m
        memory: 800Mi
    metrics:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
