# # Gateway
# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: concourse-gateway
#   namespace: concourse
# spec:
#   servers:
#     - hosts:
#         - concourse.shared.12factor.xyz
#       port:
#         name: http-issuer
#         number: 80
#         protocol: HTTP
#     - hosts:
#         - concourse.shared.12factor.xyz
#       port:
#         name: https-issuer
#         number: 443
#         protocol: HTTPS
#       tls:
#         credentialName: ingress-cert
#         mode: SIMPLE
#   selector:
#     istio: ingressgateway
# Virtual service
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: concourse-web
  namespace: default
spec:
  hosts:
    - "concourse.shared.12factor.xyz"
  gateways:
  - issuer-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: my-concourse-web.concourse.svc.cluster.local