# API service for discovery and port linking
apiVersion: v1
kind: Service
metadata:
  name: address-book-manage-api-svc
  labels:
    app: address-book-manage-api
    service: address-book-manage-api-svc
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: address-book-manage-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: address-book-manage-api
  labels:
    account: addressbookmanagement
---
# API endpoint deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-book-manage-api-deploy
  labels:
    app: address-book-manage-api
    ver: 0.1.4
    environment: production
    release: address-book-stable
    # releasesha256: "sha256:2749c56d99c7e9c85b97b5fd756a3de07471c44e27695305594ec52e143da937"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 2
  selector:
    matchLabels:
      app: address-book-manage-api
      ver: 0.1.4
    matchExpressions:
      - {key: environment, operator: In, values: [production]}
  template:
    metadata:
      labels:
        app: address-book-manage-api
        ver: 0.1.4
        environment: production
    #     sha256: "sha256:2749c56d99c7e9c85b97b5fd756a3de07471c44e27695305594ec52e143da937"
    spec:
      containers:
      - name: manage-api-container
        image: adamfowleruk/address-book-manage-api:v0.1.4
        env:
        - name: DATABASE_HOST
          value: addressbookdb.cn.adamfowler.org
        - name: PORT
          value: "3000"
        # - name: DATABASE_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: address-book-db-password
        #       key: address-book-db-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports: # Note this MUST match the port exposed by the container itself (other you'll get an unresponsive endpoint error)
        - containerPort: 3000
---