# Apply with `helm template install/kubernetes/helm/istio --namespace istio -f override.yaml > $HOME/istio.yaml`
# See https://istio.io/latest/blog/2018/aws-nlb/#generate-the-istio-manifest
gateways:
  istio-ingressgateway:
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
---